# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0002_auto_20190529_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='editor',
            new_name='profile',
        ),
    ]
