# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0004_auto_20190529_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesses',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='businesses',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesses',
            name='contact_person',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
