# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0005_auto_20190529_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesses',
            old_name='neighbourhood_id',
            new_name='business_neighbourhood',
        ),
    ]
